from turtle import *
screen=Screen()
screen.tracer(0)
bgcolor("black")
pencolor("red")
dot(530)
pencolor("black")
dot(430)
pencolor("red")
dot(415)
pencolor("black")
dot(120)
def curve01(a,d):
    for d in range(d):
        right(a)
        forward(1)
def curve02(a,d):
    for d in range(d):
        left(a)
        forward(1)
pencolor("black")
def shr(n,p):
    right(p)
    penup()
    forward(200)
    pendown()
    left(n)
    fillcolor("black")
    begin_fill()
    curve02(2,130)
    right(155)
    curve01(1,40)
    left(160)
    curve02(1.34,100)
    end_fill()
shr(180,180)
penup()
home()
shr(200,90)
penup()
home()
shr(180,-30)
done()
